### ISSUE TITLE
Repeating Missing configuration message

### ISSUE THREAD

**Issue by gorjious** [eweracs/HTLSManager#1]
When activating `Show HT Letterspacing Area` before the `HT Letterspacing Manager` this `Missing configuration` message pops up. 

Pressing OK immediately repeats the message which disables menu options, preventing opening the Manager. 

<img width="532" alt="Screenshot 2022-07-27 at 15 44 52" src="https://user-images.githubusercontent.com/23149420/181422039-dd9b51c7-8a89-458e-9f9d-9aa8810098bd.png">

**Comment by eweracs** [comment]
This should be fixed in [bc11a0a](https://github.com/eweracs/HTLSManager/commit/bc11a0a2380477a81c3fc92541b2912872b86379) and [dc0d589](https://github.com/eweracs/ShowHTLetterspacerAreas/commit/dc0d589bbc1f2f2a84f465768a24d9cf1c93f472).
