### ISSUE TITLE
HTLS failing silently

### ISSUE THREAD

**Issue by kemie** [eweracs/HTLSManager#13]
Recently found out HTLSM is just not launching. Nothing on macro panel. Just no window appears. 
Glyphs 3.3 (3326)
Python version 3.11.9 (Glyphs)

**Comment by eweracs** [comment]
Have you tried with the latest version? @schriftgestalt fixed some things in the latest pull request I merged.

**Comment by kemie** [comment]
Oh. interesting. I thought I had the latest version. I reinstalled it anyway. It now crashes glyphs when trying to launch it- but only for a specific file. I think I found the problem- it was that it was saved as a Glyphs 2 file. after saving as v3 it seems to be working. Thanks for taking a look

**Comment by eweracs** [comment]
Interesting. I'll close this issue for now, do report back if it doesn't work with the latest fixes.

**Comment by schriftgestalt** [comment]
> but only for a specific file

this is off topic, but could you send me that file?
