### ISSUE TITLE
I can't run the script

### ISSUE THREAD

**Issue by andrestelex** [eweracs/HTLSManager#3]
![image](https://user-images.githubusercontent.com/5502786/181757927-0b789d43-4152-428d-8d3b-ca6aa278bfdb.png)

After that crash, nothing happens if I run again.
Same from master or dev

**Comment by eweracs** [comment]
Can you try setting your paramDepth to a valid int? `16`, for example. Why are you using `16.00`?

I will add a fix for this case.

**Comment by andrestelex** [comment]
I can't access any UI, this happens when I run the script for the first time.

**Comment by eweracs** [comment]
In your font, if you go to Font Info > Masters, for every master, can you set the custom parameter `paramDepth` to an int, without decimals? Then the UI should work.

**Comment by andrestelex** [comment]
Got it. I didn't know I had parameters already with float values. Changed to int runs, but new error.
![image](https://user-images.githubusercontent.com/5502786/181822926-a828bb9f-9333-44f6-bf57-42a791246196.png)

**Comment by andrestelex** [comment]
It shows the error but seems to be working after that.

**Comment by eweracs** [comment]
Hi, these issues should be fixed in 1036b9bca65d77336d683fdb0a5577f86475cd41 and cc1f56f6df932b55407b386d2159fe88f45583be.
